// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "piggy": {
    "title": "Piggies",
    "name": "Name",
    "description": "Description",
    "amount": "Amount",
    "periodGoal": "Period goal",
    "endGoal": "End goal",
    "timePeriod": "Time Period",
    "initialAmount": "Initial Amount",
    "platform": "Platform",
    "balance": "Balance",
    "type": "Type",
    "new": "New Piggy" 
  },
  "transactions": {
    "createTransaction": "New Transaction - {{investment}}",
    "amount": "Amount",
    "date": "Date",
    "description": "Description"
  },
  "common": {
    "period": "Period",
    "description": "Description",
    "date": "Date",
    "select": "Select",
    "loading": "Loading",
    "save": "Save",
    "cancel": "Cancel"
  }
};
export default messages;